### ISSUE TITLE
Export the desired number of ground models and dispersion curves to text format,

### ISSUE THREAD

**Issue by Matypetzold** [jpvantassel/swprepost#13]
How do I transform a .dinver file to .txt with the geopsy command?

**If running locally**
3. After completing your inversions export the desired number of ground models and dispersion curves to text format, using the geopsy command line interface. Refer to the provided sample outputs in the 3_text directory for the naming conventions assumed by this notebook in order to be able to use the post-processing provided below.

**Comment by jpvantassel** [comment]
Hi Matypetzold,

You will need to use the command-line functions provided by Geopsy to extract the results from your .report files (you cannot extract results from the .dinver files). You will need to extract the ground models and dispersion curves to then use swprepost to process and plot the results. Note that if you use `swbatch` on DesignSafe this is done for you automatically. If you are running locally you will need to use the gpdcreport command: https://www.geopsy.org/man/gpdcreport.html from the command line. If you have questions how to do this, please send them to the Geopsy forum as this is a Geopsy-related issue.
