### ISSUE TITLE
Issue in the Python code 'example_swinvert_workflow.ipynb'

### ISSUE THREAD

**Issue by AniketSanjayDesai** [jpvantassel/swprepost#5]
Hello.
I am a Ph.D. Research Scholar.
While running the code 'example_swinvert_workflow.ipynb' which is in the folder 'adv', while running the cell below the section 'If running remotely on DesignSafe-CI', it shows the message 
'File "<ipython-input-8-a947b74337b6>", line 93
    from agavepy.async import AgaveAsyncResponse
                          ^
SyntaxError: invalid syntax'.

I request you to let me know what can be done.

**Comment by jpvantassel** [comment]
Hi,

Can you please confirm you are running the notebook using the DesignSafe-CI Jupyterhub accessible at https://www.designsafe-ci.org/  and not running locally, via Google collab, or another Jupyter hub.

**Comment by AniketSanjayDesai** [comment]
Hi,
Thank you for the prompt reply and letting me know the correct way. Actually I ran it locally earlier. Now, I have run using the DesignSafe-CI Jupyterhub accessible at https://www.designsafe-ci.org/ and the error mentioned above is not shown now. 
However, I have a query. 
In the above code, one dispersion curve with standard deviation and multiple parameterizations can be given.
It is mentioned in Vantassel & Cox (2021) that N=250 realizations of dispersion curves were inverted with a single 3-layer parameterization on TACC's cluster stampede2.
How to simultaneously invert multiple dispersion curves (for example, 250) with a single layer parameterization?

**Comment by jpvantassel** [comment]
Glad the issue is resolved. You can invert multiple .target files by placing them in the targets directory.
