### ISSUE TITLE
Unable to parse geopsy files in Linux

### ISSUE THREAD

**Issue by arkottke** [jpvantassel/swprepost#6]
The metadata on the output of `gpdc` aren't consistent between the Rayleigh and Love dispersion curves. I don't quite understand why it is. See the example output from `gpdc`.

[tmp.dc.txt](https://github.com/jpvantassel/swprepost/files/7552222/tmp.dc.txt)

**Comment by jpvantassel** [comment]
Hi @arkottke ,
Thank you for letting me know about this and providing the PR.
Can you provide the Geopsy version (i.e., `geopsy --version`)?

**Comment by arkottke** [comment]
I just realized that I never responded to this. I just pulled and rebuilt geopsy, but the difference persists. Here are the versions:
```
❯ geopsy --version
Versions:
  Qt                  5.15.2
  QGpCoreTools        2.4.2 from 3.4.3-preview
      (commit 33d7a93616e30a3d511fa67ad3f5da9da1a4aac6)
  QGpGuiTools         2.4.2 from 3.4.3-preview
      (commit 478ff49d6d6ec28d92b21ec9bfcef9f5d343b065)
  QGpCoreMath         1.4.2 from 3.4.3-preview
      (commit 306e3c199829ace6cbde6b242503355428580d05)
  SciFigs             3.3.2 from 3.4.3-preview
      (commit cec1d051784e8ee1d9774230fb96c1bb0b618aa0)
  QGpGuiMath          1.3.1 from 3.4.3-preview
      (commit 8e80e068f4f3b16a30e8fb8dff21177f25a58da6)
  GeopsyCore          4.4.2 from 3.4.3-preview
      (commit e203ef616ad260d862af4bb4aa9cc888b8a8a862)
  GeopsyGui           3.4.1 from 3.4.3-preview
      (commit 905aba82a1928b07b3fd61dec384b9448698c80b)
  GeopsySLink         2.0.3 from 3.4.3-preview
      (commit 2f01f562d775a4ddcdfc6a3b388c2ecb0cbb3a9a)
  GeopsySLinkGui      2.0.2 from 3.4.3-preview
      (commit f6e61f2761b9ab1fa13c821e2a94732db60abf4f)
  geopsy              3.3.3 from 3.4.3-preview
      (commit fb3d54b85a28e6ba741794e0cb6666d0b25c0167)

❯ gpdc --version
Versions:
  Qt                  5.15.2
  QGpCoreTools        2.4.2 from 3.4.3-preview
      (commit 33d7a93616e30a3d511fa67ad3f5da9da1a4aac6)
  QGpCoreMath         1.4.2 from 3.4.3-preview
      (commit 306e3c199829ace6cbde6b242503355428580d05)
  QGpCoreWave         2.2.0 from 3.4.3-preview
      (commit 18e08f9fd358a9e504047ec288ca4ab71a7c9851)
  gpdc                1.0.4 from 3.4.3-preview
      (commit c3b27d05c7d31c8194b5f8ced8b689e90feb401f)
```

**Comment by jpvantassel** [comment]
Thanks @arkottke, I will dig into this. Note that in the upcoming release of _swprepost_, I will only be supporting two specific versions of Geopsy a "historic" version (currently v2.10.1) and a "latest" version (currently v3.4.2) to avoid future problems like this and to make maintaining _swprepost_ more sustainable. Will follow up with you shortly.

**Comment by jpvantassel** [comment]
Hi @arkottke 
After looking into it, I do not believe it is an OS-related issue, but a difference between Geopsy v2 and v3. _swprepost_ prior to and including v1.0.0 only officially supported Geopsy v2, but now with v2.0.0 I will be adding support for v3. Regardless, I was able to reproduce the issue and create a fix. See commit 9e6c77b for details.
Thanks again for bringing this to my attention.
